package com.studentsystem.consts;

import android.graphics.BitmapFactory;

import com.studentsystem.MyApplication;
import com.studentsystem.R;
import com.studentsystem.bean.Admin;
import com.studentsystem.bean.Course;
import com.studentsystem.bean.Student;
import com.studentsystem.db.DBManager;
import com.studentsystem.utils.BitmapUtil;

public class Consts {

    /**
     * true表示没服务器端，所有数据都保存在本地SQLite
     */
    public static final boolean IS_LOCAL = true;

    /**
     * 构造数据插入本地数据库
     * 只有IS_LOCAL==true的时候才有用
     */
    public static void createStudent() {
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S1")
            .setName("东方爵")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("2000-12-21")
            .setSex("男")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("河北")
            .setCollege("信息科学与技术")
            .setMajor("软件工程")
            .setClassIn("1801"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S2")
            .setName("曾恬然")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("2000-12-21")
            .setSex("男")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("河南")
            .setCollege("信息科学与技术")
            .setMajor("软件工程")
            .setClassIn("1805"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S3")
            .setName("诸葛蕤")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("1999-12-21")
            .setSex("女")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("山东")
            .setCollege("信息科学与技术")
            .setMajor("软件工程")
            .setClassIn("1801"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S4")
            .setName("雍书仪")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("2001-12-21")
            .setSex("男")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("河北")
            .setCollege("信息科学与技术")
            .setMajor("软件工程")
            .setClassIn("1802"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S5")
            .setName("其德曜")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("2002-12-21")
            .setSex("男")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("广东")
            .setCollege("信息科学与技术")
            .setMajor("软件工程")
            .setClassIn("1901"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S6")
            .setName("于丹蝶")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("2001-12-21")
            .setSex("女")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("河北")
            .setCollege("信息科学与技术")
            .setMajor("计算机科学")
            .setClassIn("1802"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S7")
            .setName("张阳晖")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("1998-12-21")
            .setSex("男")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("河北")
            .setCollege("信息科学与技术")
            .setMajor("通信工程")
            .setClassIn("1802"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S8")
            .setName("蒲静柏")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("2000-12-21")
            .setSex("男")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("新疆")
            .setCollege("信息科学与技术")
            .setMajor("软件工程")
            .setClassIn("1801"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S9")
            .setName("罗娟巧")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("2000-11-21")
            .setSex("女")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("黑龙江")
            .setCollege("信息科学与技术")
            .setMajor("软件工程")
            .setClassIn("1803"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S10")
            .setName("闫淑")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("2000-12-21")
            .setSex("女")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("广西")
            .setCollege("信息科学与技术")
            .setMajor("软件工程")
            .setClassIn("1803"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S11")
            .setName("鲁若山")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("2000-12-21")
            .setSex("男")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("内蒙古")
            .setCollege("信息科学与技术")
            .setMajor("软件工程")
            .setClassIn("1801"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S12")
            .setName("王溪澈")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("1996-12-21")
            .setSex("男")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("河北")
            .setCollege("信息科学与技术")
            .setMajor("软件工程")
            .setClassIn("1601"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S13")
            .setName("巩幼霜")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("1997-12-21")
            .setSex("男")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("甘肃")
            .setCollege("信息科学与技术")
            .setMajor("软件工程")
            .setClassIn("1601"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S14")
            .setName("章佳禄")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("2002-12-21")
            .setSex("女")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("河北")
            .setCollege("信息科学与技术")
            .setMajor("软件工程")
            .setClassIn("1901"));
        DBManager.getInstance().getStudentDao().insertData(new Student()
            .setStuId("S15")
            .setName("祝雨伯")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("2000-12-21")
            .setSex("男")
            .setPhone("131442351")
            .setEmail("androiddev@163.com")
            .setHometown("浙江")
            .setCollege("信息科学与技术")
            .setMajor("软件工程")
            .setClassIn("1901"));
    }
    public static void createAdmin() {
        DBManager.getInstance().getAdminDao().insertData(new Admin()
            .setAdminId("A1")
            .setName("张翠山")
            .setAvatar(BitmapUtil.bitmap2Bytes(BitmapFactory.decodeResource(MyApplication.getInstance().getResources(), R.mipmap.default_avatar)))
            .setPassword("1")
            .setBirthday("1956-12-21")
            .setSex("男")
            .setPhone("131442351")
            .setEmail("zhangcuishan@163.com")
            .setHometown("广东")
            .setCollege("信息科学与技术"));
    }
    public static void createCourse() {
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C1")
            .setName("计算机基础")
            .setTotalTime(36)
            .setCredit(3)
            .setTeacher("张无忌")
            .setObligatory("必修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C2")
            .setName("大学英语")
            .setTotalTime(48)
            .setCredit(5)
            .setTeacher("乔峰")
            .setObligatory("必修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C3")
            .setName("C语言")
            .setTotalTime(36)
            .setCredit(3.5f)
            .setTeacher("张翠山")
            .setObligatory("必修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C4")
            .setName("C++")
            .setTotalTime(24)
            .setCredit(2)
            .setTeacher("张翠山")
            .setObligatory("选修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C5")
            .setName("计算机组成原理")
            .setTotalTime(36)
            .setCredit(3)
            .setTeacher("张翠山")
            .setObligatory("必修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C6")
            .setName("计算机网络")
            .setTotalTime(32)
            .setCredit(2.5f)
            .setTeacher("张无忌")
            .setObligatory("必修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C7")
            .setName("高等数学")
            .setTotalTime(48)
            .setCredit(6)
            .setTeacher("张无忌")
            .setObligatory("必修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C8")
            .setName("矩阵原理")
            .setTotalTime(24)
            .setCredit(2)
            .setTeacher("张无忌")
            .setObligatory("选修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C9")
            .setName("计算方法学")
            .setTotalTime(24)
            .setCredit(2)
            .setTeacher("乔峰")
            .setObligatory("选修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C10")
            .setName("电路原理")
            .setTotalTime(36)
            .setCredit(3.5f)
            .setTeacher("阮朱")
            .setObligatory("必修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C11")
            .setName("数据结构")
            .setTotalTime(36)
            .setCredit(4)
            .setTeacher("张翠山")
            .setObligatory("必修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C12")
            .setName("日语")
            .setTotalTime(24)
            .setCredit(3)
            .setTeacher("赵敏")
            .setObligatory("选修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C13")
            .setName("德语")
            .setTotalTime(24)
            .setCredit(2.5f)
            .setTeacher("周芷若")
            .setObligatory("选修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C14")
            .setName("Java程序设计")
            .setTotalTime(36)
            .setCredit(4)
            .setTeacher("张无忌")
            .setObligatory("必修"));
        DBManager.getInstance().getCourseDao().insertData(new Course()
            .setCourseId("C15")
            .setName("高等软件工程")
            .setTotalTime(36)
            .setCredit(4.5f)
            .setTeacher("张翠山")
            .setObligatory("选修"));
    }
}
